"use client";

import type { Metadata } from "next";
import "../styles/globals.css";
import Image from "next/image";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ModeToggle } from "@/components/theme/mode-toggle";

// export const metadata: Metadata = {
//   title: "Danmi Pilates",
//   description: "Generated by Terry Lee",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="mt-5 ml-6">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <h1>
            <a href="/">
              <Image
                src="/logo.svg"
                alt="Danmi Logo"
                width={50}
                height={2}
                priority
              />
            </a>
          </h1>
          <ModeToggle className={"absolute top-6 right-6"} />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
