"use client";

import type { Metadata } from "next";
import "../styles/globals.css";
import Image from "next/image";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { ModeToggle } from "@/components/theme/mode-toggle";
import { NavigationMenuDemo } from "@/components/Header/menu";
import Footer from "@/components/footer/footer";

// export const metadata: Metadata = {
//   title: "Danmi Pilates",
//   description: "Generated by Terry Lee",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html>
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="mt-5 ml-6">
              <div className="flex justify-center">
                <a href="/">
                  <Image
                    className="absolute left-6"
                    src="/logo.svg"
                    alt="Danmi Logo"
                    width={50}
                    height={2}
                    priority
                  />
                </a>

                <NavigationMenuDemo />

                <ModeToggle className={"absolute top-6 right-6"} />
              </div>
            </div>
          </ThemeProvider>
          <div className="mt-10 ml-6">{children}</div>
          <footer className="fixed bottom-0 mb-10 ml-6">
            <Footer />
          </footer>
        </body>
      </html>
    </>
  );
}
