import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Danmi Pilates Admin",
  description: "Generated by Terry Lee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <h1>
          <a href="/">Danmi</a>
        </h1>
        {children}
      </body>
    </html>
  );
}
